name: ICIS Data Download

on:
  # Schedule the workflow to run daily at 00:00 UTC
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight UTC
  # Allow manual trigger from the GitHub Actions tab
  workflow_dispatch:

jobs:
  run_script:
    runs-on: ubuntu-latest # Use the latest Ubuntu runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Action to check out your repository code

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9' # Or your desired Python version (e.g., '3.10', '3.11')

      - name: Install system dependencies for Chrome and Selenium
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser chromium-chromedriver # Installs Chromium and its driver

      - name: Install Python dependencies
        run: |
          pip install --upgrade pip
          # Removed google-colab-selenium as it's not needed for GitHub Actions
          pip install pygsheets retrying pandas requests selenium Pillow gspread gspread-dataframe pymupdf

      - name: Create temporary downloads directory
        run: |
          mkdir -p /tmp/downloads # Ensure this matches DOWNLOAD_DIR in your Python script

      - name: Create service account key file
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
        run: |
          echo "$GCP_SA_KEY" > service_account_key.json
        # IMPORTANT: This creates the file only during the workflow run.
        # It's NOT committed to your repository.

      - name: Run Python script
        env:
          # Set your API key from GitHub Secrets for ImageService
          DASHSCOPE_API_KEY: ${{ secrets.DASHSCOPE_API_KEY }}
          # Set the CHROMEDRIVER_PATH.
          CHROMEDRIVER_PATH: /usr/bin/chromedriver
          # Set ICIS login credentials from GitHub Secrets
          ICIS_USERNAME: ${{ secrets.ICIS_USERNAME }}
          ICIS_PASSWORD: ${{ secrets.ICIS_PASSWORD }}
          # Set RISI login credentials from GitHub Secrets (used in risi_main fallback)
          RISI_USERNAME: ${{ secrets.RISI_USERNAME }}
          RISI_PASSWORD: ${{ secrets.RISI_PASSWORD }}
        run: |
          # Execute your main script.
          # Ensure this path is correct if your Python file is in a subfolder.
          python ICIS_Data_Download.py
